CREATE TABLE  `sgml`.`forex` (
`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`rate` DECIMAL( 8 ) NULL DEFAULT NULL ,
`currency` TEXT NULL DEFAULT NULL ,
PRIMARY KEY (  `created` )
) ENGINE = INNODB DEFAULT CHARSET=utf8;
